# extract_features_opencv_v2.py
import os
import csv
import numpy as np
import pandas as pd

IN_DIR = "collected_opencv"
OUT_FILE = "features_opencv.csv"

# expected numeric columns: pose 33*(x,y,z,vis)=132 ; hand 21*(x,y)=42
EXPECTED_POSE_LEN = 33 * 4
EXPECTED_HAND_LEN = 21 * 2
EXPECTED_FEATURES_LEN = EXPECTED_POSE_LEN + EXPECTED_HAND_LEN

def read_csv_rows(path):
    with open(path, "r", newline='') as f:
        reader = csv.reader(f)
        rows = list(reader)
    return rows

def parse_filename(fname):
    # safe parse: label may contain underscores, timestamp is last part before extension
    base = os.path.splitext(fname)[0]
    if "_" not in base:
        return base, ""
    label, ts = base.rsplit("_", 1)
    return label, ts

def row_to_features(row):
    # row layout generated by collect script: [label, timestamp, <pose 132 values>, <hand 42 values>]
    if len(row) < 2 + EXPECTED_FEATURES_LEN:
        return None
    # drop the first two columns (label + timestamp)
    features = row[2:2 + EXPECTED_FEATURES_LEN]
    try:
        features = [float(x) for x in features]
    except Exception:
        return None
    return features

def main():
    files = [f for f in os.listdir(IN_DIR) if f.lower().endswith(".csv")]
    all_rows = []
    processed_files = 0
    skipped_files = []
    processed_samples = 0
    for f in files:
        path = os.path.join(IN_DIR, f)
        try:
            label, ts = parse_filename(f)
            rows = read_csv_rows(path)
            processed_files += 1
            for r in rows[1:]:  # skip header
                if not r:
                    continue
                # Some CSVs might have been saved with extra separators - be defensive
                features = row_to_features(r)
                if features is None:
                    # try to handle if row length is larger: take last EXPECTED_FEATURES_LEN values
                    if len(r) >= 2 + EXPECTED_FEATURES_LEN:
                        tail = r[-EXPECTED_FEATURES_LEN:]
                        try:
                            tail = [float(x) for x in tail]
                            features = tail
                        except Exception:
                            features = None
                if features is None:
                    # skip this row
                    continue
                all_rows.append([label] + features)
                processed_samples += 1
        except Exception as e:
            skipped_files.append((f, str(e)))
            print(f"Skipping {path} due to error: {e}")

    if processed_samples == 0:
        print(f"No valid feature rows found. Processed {processed_files} files, skipped {len(skipped_files)} file(s).")
        if skipped_files:
            print("Skipped files (one-line reasons):")
            for sf, reason in skipped_files:
                print(f" - {sf}: {reason}")
        # write empty CSV header for downstream clarity
        cols = ["label"] + [f"f{i}" for i in range(EXPECTED_FEATURES_LEN)]
        pd.DataFrame(columns=cols).to_csv(OUT_FILE, index=False)
        print(f"Features saved to {OUT_FILE} with 0 rows")
        return

    cols = ["label"] + [f"f{i}" for i in range(EXPECTED_FEATURES_LEN)]
    df = pd.DataFrame(all_rows, columns=cols)
    df.to_csv(OUT_FILE, index=False)
    print(f"Features saved to {OUT_FILE} with {len(df)} rows (from {processed_files} files).")
    if skipped_files:
        print("Skipped files (one-line reasons):")
        for sf, reason in skipped_files:
            print(f" - {sf}: {reason}")

if __name__ == "__main__":
    os.makedirs(IN_DIR, exist_ok=True)
    main()
